import { Check, CreditCard, Sparkles, Users, WalletCards } from 'lucide-react';

const plans = [
  { name: 'Free', price: 'C$0', note: 'Validate the platform', credits: 25, icon: Sparkles, features: ['Business workspace', 'Selected free tools', '25 monthly credits', 'Community access'] },
  { name: 'Pro SMB', price: 'C$49', note: 'Beta price hypothesis', credits: 150, icon: WalletCards, features: ['Everything in Free', 'Premium analysis tools', '150 monthly credits', 'Saved reports and exports', 'Priority tool releases'] },
  { name: 'Business', price: 'C$149', note: 'Beta price hypothesis', credits: 500, icon: Users, features: ['Everything in Pro SMB', 'Team workspace', 'Agent Control Centre', 'Approval and audit controls', '500 monthly credits'] },
];

export default function CommercialCenter({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[170] overflow-y-auto bg-[#0e2927]/60 p-3 backdrop-blur-sm sm:p-6">
    <div className="mx-auto max-w-6xl rounded-[28px] bg-[#f7f6f1] shadow-2xl">
      <header className="flex flex-col gap-4 border-b border-[#dae3de] bg-white px-5 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-8">
        <div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#39796f]">Commercial beta · Canada</p><h2 className="mt-1 text-3xl font-semibold text-[#203a37]">Plans & credits</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#71807c]">The commercial layer is credit-based so customers can use different tools without buying a separate subscription for each one.</p></div>
        <button onClick={onClose} className="self-start rounded-xl border border-[#d7dfda] px-4 py-2 text-sm font-semibold text-[#526762]">Close</button>
      </header>
      <div className="p-5 sm:p-8">
        <div className="rounded-2xl border border-[#eadfbd] bg-[#fff8e8] p-4 text-sm leading-6 text-[#705f39]">Prices shown are product hypotheses for validation, not final published pricing. No billing is activated in this build until tax, payment processing, refund terms and Canadian corporate setup are confirmed.</div>
        <div className="mt-6 grid gap-5 lg:grid-cols-3">{plans.map((plan) => { const Icon = plan.icon; return <article key={plan.name} className={`rounded-[24px] border bg-white p-6 ${plan.name === 'Pro SMB' ? 'border-[#8ebbb0] shadow-[0_18px_40px_rgba(45,111,102,.12)]' : 'border-[#dfe5e0]'}`}><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#edf4f0] text-[#2d6f66]"><Icon size={21}/></span>{plan.name === 'Pro SMB' && <span className="rounded-full bg-[#e7f3ed] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#39796f]">Recommended beta</span>}</div><h3 className="mt-5 text-xl font-semibold text-[#304b46]">{plan.name}</h3><div className="mt-3 flex items-end gap-2"><span className="text-4xl font-semibold tracking-tight text-[#203a37]">{plan.price}</span><span className="pb-1 text-sm text-[#788783]">/ month</span></div><p className="mt-1 text-xs font-semibold text-[#98783d]">{plan.note}</p><div className="mt-5 rounded-xl bg-[#f1f5f1] p-3"><p className="text-xs text-[#75837f]">Included monthly usage</p><p className="mt-1 text-lg font-semibold text-[#356e65]">{plan.credits} credits</p></div><ul className="mt-5 grid gap-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-[#63736f]"><Check size={16} className="mt-0.5 shrink-0 text-[#43816f]"/>{feature}</li>)}</ul><button disabled className="mt-6 w-full rounded-xl border border-[#d6dfda] px-4 py-2.5 text-sm font-semibold text-[#8a9793]">Billing not activated</button></article> })}</div>
        <section className="mt-7 grid gap-5 lg:grid-cols-[1fr_.8fr]"><div className="rounded-2xl border border-[#dfe5e0] bg-white p-6"><div className="flex items-center gap-2 text-[#39796f]"><CreditCard size={19}/><h3 className="font-semibold">Credit rules</h3></div><div className="mt-4 grid gap-3 text-sm leading-6 text-[#687873]"><p><strong className="text-[#405a55]">Quote before consume:</strong> premium tools show the credit cost before the run starts.</p><p><strong className="text-[#405a55]">Per-tenant limits:</strong> owners set spending limits and agent cost ceilings.</p><p><strong className="text-[#405a55]">Failure handling:</strong> failed paid runs are eligible for automatic credit reversal when no usable result is produced.</p><p><strong className="text-[#405a55]">No hidden autonomous spend:</strong> background agents cannot exceed their configured limit or perform material actions without the required approval.</p></div></div><div className="rounded-2xl bg-[#173d39] p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#9dd0c4]">Expert services</p><h3 className="mt-2 text-xl font-semibold">Need implementation, not another report?</h3><p className="mt-3 text-sm leading-6 text-[#c7d8d4]">Diagnostics and tools can lead into scoped B2B implementation or managed-agent services. Those engagements are quoted separately and remain human-approved.</p></div></section>
      </div>
    </div>
  </div>;
}
